"""Alter sessions table

Revision ID: 0ebb1b616c59
Revises: 8c34320f6f92
Create Date: 2026-10-05 15:34:16.361999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebb1b616c59'
down_revision: Union[str, Sequence[str], None] = '8c34320f6f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_id', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('sessions_session_token_key'), 'sessions', type_='unique')
    op.create_unique_constraint(None, 'sessions', ['session_id'])
    op.drop_column('sessions', 'session_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'sessions', type_='unique')
    op.create_unique_constraint(op.f('sessions_session_token_key'), 'sessions', ['session_token'], postgresql_nulls_not_distinct=False)
    op.drop_column('sessions', 'session_id')

