"""add mpin lockout fields

Revision ID: 5bb189dc967e
Revises: fe46831389ab
Create Date: 2026-09-29 16:34:26.087122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb189dc967e'
down_revision: Union[str, Sequence[str], None] = 'fe46831389ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users',
        sa.Column(
            'mpin_failed_attempts',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'mpin_locked_until',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )

    op.alter_column(
        'users',
        'mpin_failed_attempts',
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mpin_locked_until')
    op.drop_column('users', 'mpin_failed_attempts')
